export { default as MainBanner } from './MainBanner';
export { default as Chroma } from './Chroma';
export { default as Company } from './Company';
export { default as Process } from './Process';
export { default as Education } from './Education';
export { default as Portfolio } from './Portfolio';
export { default as Contact } from './Contact';
export { default as Live } from './Live';
export { default as With } from './With';